"""Geometry capability seam. Shapes are opaque to orchestration.

Operations must not mutate input geometry. copy() returns an independent B-Rep
for history snapshots; derived triangulation caches are not editable geometry.
"""
from typing import Protocol, runtime_checkable


@runtime_checkable
class GeometryBackend(Protocol):
    name: str

    def box(self, size, origin) -> object: ...
    def cylinder(self, radius, height, origin) -> object: ...
    def sphere(self, radius, center) -> object: ...
    def extrude(self, profile, height) -> object: ...
    def revolve(self, profile, angle_degrees) -> object: ...
    def sweep(self, profile, path) -> object: ...
    def loft(self, profiles, stations) -> object: ...
    def boolean(self, kind, left, right) -> object: ...
    def transform(self, shape, matrix) -> object: ...
    def translate(self, shape, vector) -> object: ...
    def fillet(self, shape, radius, edge_ids=None, selector=None) -> object: ...
    def chamfer(self, shape, distance, edge_ids=None, selector=None) -> object: ...
    def shell(self, shape, thickness, face_ids=None) -> object: ...
    def hole(self, shape, position, direction, diameter, depth, through) -> object: ...
    def mirror(self, shape, plane, origin=None, normal=None, keep_original=False) -> object: ...
    def linear_pattern(self, shape, direction, spacing, count) -> object: ...
    def circular_pattern(self, shape, origin, direction, count) -> object: ...
    def query(self, shape, point=None) -> dict: ...
    def section(self, shape, origin, normal) -> dict: ...
    def measure(self, shape) -> dict: ...
    def contains(self, shape, point) -> bool: ...
    def bounds(self, shape) -> list[list[float]]: ...
    def topology(self, shape) -> dict: ...
    def tessellate(self, shape, chord) -> dict: ...
    def tessellate_faces(self, shape, face_ids, chord) -> dict: ...
    def copy(self, shape): ...
    def export_step(self, shape, path: str) -> None: ...
    def export_gltf(self, shape, path: str, chord: float) -> None: ...
    def export_brep_bytes(self, shape) -> bytes: ...
    def import_brep_bytes(self, payload: bytes): ...
